file: screen_names.csv  #Filename for list of twitter IDs.
config: ./twitter  #Spot for the configuration.
data: ./data      #Filename for data.
consumer_key: ******************************************
consumer_secret: ******************************************
access_token: ******************************************
access_token_secret: ******************************************
sleep_interval: 5 ## twitter api access limit Requests / 15-min window (user auth) 180 => 5 sec/request
twitter_cutoff: 3195 #Twitter cuts off at 3195 tweets per user.
